Unified base mode colors and helper function
JGreenlee/e-mission-common pull request #1
Opened 2024-07-09 15:09 UTC by louisg1337

Moved `modeColors`, `BaseModes`, and `getBaseModeByKey` from [`diaryHelper.ts`](https://github.com/e-mission/e-mission-phone/blob/master/www/js/diary/diaryHelper.ts) to `e-mission-common` for centralized use between `e-mission` platforms. 

**Testing Done**
- Used npm link to add my local `e-mission-common` as a dependency in `e-mission-phone`
- Then replaced the objects and function in favor of our `e-mission-common` version as shown below.
  ```
  export const modeColors = base_mode_colors.modeColors;
  export const BaseModes = base_mode_colors.BaseModes;
  export const getBaseModeByKey = base_mode_colors.getBaseModeByKey;
  ```

2024-07-09 15:45 UTC, JGreenlee requested changes
Great job setting this up. Glad you were able to use the compile script and use npm link to test the compiled JS in the context of e-mission-phone

You should try to test the source Python code as well

2024-07-09 15:45 UTC, JGreenlee commented on src/emcommon/diary/base_mode_colors.py
> +modeColors = {
```suggestion
mode_colors = {
```
Use snake_case for python code

2024-07-09 15:45 UTC, JGreenlee commented on src/emcommon/diary/base_mode_colors.py
> +BaseModes = {
```suggestion
BASE_MODES = {
```
uppercase SNAKE_CASE to signify that this is a constant

2024-07-09 15:45 UTC, JGreenlee commented on src/emcommon/diary/base_mode_colors.py
> +def getBaseModeByKey(motionName):
```suggestion
def get_base_mode_by_key(motionName):
```
snake_case

2024-07-09 15:45 UTC, JGreenlee commented on src/emcommon/diary/base_mode_colors.py
> +    return (pop and BaseModes[pop]) or BaseModes["UNKNOWN"]
`toUpperCase`, `split`, `pop` are Javascript methods that don't exist in python. the compiled JS might work, but this wouldn't work in Python.

rewrite with the appropriate python methods and then test the compiled JS

2024-07-09 20:01 UTC, louisg1337 commented
Thanks for the feedback @JGreenlee! I took some time to incorporate your requests and actually properly test the python implementation, in which I found a few more bugs that I also addressed in this latest push. Also, I did have to change `toUpperCase()` to `upper()`, but apparently `split()` and `pop()` are both functions in python as well, so I ended up getting lucky with that. 

**Testing Done**
- I did the same tests as above, where I plugged in our `e-mission-common`'s versions of our functions in `diaryHelper.ts` and I got no errors.
- I tested the python implementation of `get_base_mode_by_key()` as follows...
  ```py
  print(get_base_mode_by_key("AIR"))
  print(get_base_mode_by_key("HELLO"))
  > {'name': 'AIR', 'icon': 'airplane', 'color': '#bf5900'}
  > {'name': 'UNKNOWN', 'icon': 'help', 'color': '#555555'}
  ```
- I then did the same for the javascript implementation...
  ```js
  console.log(get_base_mode_by_key("AIR"))
  console.log(get_base_mode_by_key("HELLO"))
  > {'name': 'AIR', 'icon': 'airplane', 'color': '#bf5900'}
  > {'name': 'UNKNOWN', 'icon': 'help', 'color': '#555555'}
  ```

2024-07-10 17:32 UTC, JGreenlee approved these changes
Great! Now can you create a corresponding PR on e-mission-phone? Search for places where `getBaseModeByKey` was imported from `diaryHelper`. Replace those by importing `base_mode_colors` from `e-mission-common` and calling `base_mode_colors.get_base_mode_by_key`.
Then you can remove `getBaseModeByKey`.

2024-07-11 15:53 UTC, louisg1337 commented
Sounds good, just released a [PR](https://github.com/e-mission/e-mission-phone/pull/1164) with those changes!

2024-07-19 20:11 UTC, merged