Add pytest in GitHub Actions
JGreenlee/e-mission-common pull request #9
Opened 2024-09-19 20:28 UTC by jpfleischer

This change adds an automated pytest using the conda environment.
The workflow is inspired from the one in e-mission-server: https://github.com/e-mission/e-mission-server/blob/master/.github/workflows/test-with-manual-install.yml

2024-09-19 22:59 UTC, JGreenlee requested changes
Thanks for the contribution. This has been on my todo list.

I think this can be significantly simplified and expanded to include the Javascript tests as well

2024-09-19 22:59 UTC, JGreenlee commented on bin/run_pytest.sh
there's no diff here so I'm guessing you just made it executable, which is good

2024-09-19 22:59 UTC, JGreenlee commented on .github/workflows/pytest.yml
> +    - cron:  '5 4 * * 0'
Since the tests are pretty lightweight and finish within a couple seconds (at least for now), you can have it run on every push on any branch

2024-09-19 22:59 UTC, JGreenlee commented on .github/workflows/pytest.yml
> +  build:
Ultimately I'd like to have 2 jobs that run in parallel, one for `pytest` and one for `jest`. Maybe this workflow can be named more generally

2024-09-19 22:59 UTC, JGreenlee commented on .github/workflows/pytest.yml
> +        PYTHONPATH=./src pytest test --asyncio-mode=auto
I don't think all of this is needed because `setup.sh` handles setting up the conda environment.

Can it just run `setup.sh` followed by `run_pytest.sh`?

2024-09-20 09:01 UTC, jpfleischer commented
I have implemented all of the above. Thank you for your feedback.
Please let me know if you want the js compilation automated

2024-10-23 04:21 UTC, JGreenlee reviewed
I apologize for this late feedback; I wrote these comments weeks ago but had left them "pending" so they were not visible yet.

2024-10-23 16:41 UTC, merged